accounts/urls.py
from django.urls import path

from accounts.views import RegisterView, LoginView, ProfileView, logout_view, UserChangeView

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("account/<int:pk>/", ProfileView.as_view(), name="account"),
    path("logout/", logout_view, name="logout"),
    path("update/<int:pk>/", UserChangeView.as_view(), name="user_update")
]

hh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        to=get_user_model(),
        related_name="profile",
        on_delete=models.CASCADE,
        verbose_name="User profile"
    )

    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to="profile_picture"
    )
    is_corporate = models.BooleanField(
        null=True,
        blank=True,
    )
    phone_number = PhoneNumberField(
        blank=False,
        null=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    # @receiver(post_save, sender=get_user_model())
    # def update_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)
    #     instance.profile.save()

accounts/forms/auth_forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField

from accounts.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.EmailInput
    )
    is_corporate = forms.BooleanField(
        required=False)
    avatar = forms.ImageField(
        required=False)
    phone_number = PhoneNumberField(required=True)

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email", "is_corporate", "avatar", "phone_number")


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Your username')
    password = forms.CharField(required=True, label='Password', widget=forms.PasswordInput)


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'phone_number']

accounts/forms/regster_forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField


class SignUpForm(UserCreationForm):

    email = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.EmailInput
    )
    is_corporate = forms.BooleanField(required=False
    )
    avatar = forms.ImageField(
        required=False)
    phone_number = PhoneNumberField(
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email", "is_corporate", "avatar", "phone_number")

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView

from accounts.forms import SignUpForm


class RegisterView(CreateView):
    template_name = "register.html"
    form_class = SignUpForm
    success_url = "/admin"

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.phone_number = form.cleaned_data.get("phone_number")
            user.profile.is_corporate = form.cleaned_data.get("is_corporate")
            user.profile.avatar = form.cleaned_data.get("avatar")
            user.save()
            login(request, user)
            return redirect("index")
        context = {}
        context["form"] = form
        return self.render_to_response(context)

accounts/views/auth_views.py
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView

from accounts.forms import SignUpForm, LoginForm, UserChangeForm, ProfileChangeForm


class RegisterView(CreateView):
    template_name = "register.html"
    form_class = SignUpForm
    success_url = "/admin"

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        print(form.is_bound)
        if form.is_valid():
            user = form.save()
            # user.refresh_from_db()
            user.profile.phone_number = form.cleaned_data.get("phone_number")
            user.profile.is_corporate = form.cleaned_data.get("is_corporate")
            user.profile.avatar = form.cleaned_data.get("avatar")
            user.profile.save()
            login(request, user)
            return redirect("index")
        context = dict()
        print(context)
        context["form"] = form
        print(form.fields)
        print(form)
        print(context)
        return self.render_to_response(context)


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        # next = request.GET.get('next')
        # form_data = {} if not next else {'next': next}
        form = self.form
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('login')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        # next = form.cleaned_data.get('next')
        user = authenticate(request, username=username, password=password)
        if not user:
            return redirect("login")
        login(request, user)
        # if next:
        #     return redirect(next)
        return redirect("account", pk=user.pk)


def logout_view(request):
    logout(request)
    return redirect('index')


class ProfileView(DetailView):
    model = get_user_model()
    template_name = "user_detail.html"
    context_object_name = "user_obj"

    # def get_context_data(self, **kwargs):
    #     posts = self.object.posts.all()
    #     print(request.user)
    #     kwargs["posts"] = posts
    #     return super().get_context_data(**kwargs)

    # def post(self, request, *args, **kwargs):
    #     account_id = request.POST.get("cust_id")
    #     account = Account.objects.get(pk=account_id)
    #     user = request.user
    #     # здесь логика по отклику на вакансию/резюме
    #     return redirect('index')


class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'partial/partial_user_change.html'
    context_object_name = 'user_obj'
    data = dict()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        data = self.data
        data['html_forms'] = render_to_string(self.template_name, self.get_context_data(), request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form, request)
        else:
            return self.form_invalid(form, profile_form, request)

    def form_valid(self, form, profile_form, request):
        self.object = form.save()
        profile_form.save()
        data = self.data
        data['forms_are_valid'] = True
        user_obj = self.object
        data['html_general_profile_info'] = render_to_string("partial/partial_general_profile_info.html", {"user_obj": user_obj})
        return JsonResponse(data)

    def form_invalid(self, form, profile_form, request):
        data = self.data
        data['forms_are_valid'] = False
        context = self.get_context_data(form=form, profile_form=profile_form)
        data['html_forms'] = render_to_string(self.template_name, context, request=request)
        return JsonResponse(data)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
            print(form_kwargs)
        print(form_kwargs)
        print(self.object.profile.avatar)
        return ProfileChangeForm(**form_kwargs)

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block menu %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="d-flex justify-content-center">
                <div class="col-lg-4 col-md-8 col-sm-11">
                    <div class="card">
                        <div class="container hh-logo col-5 mt-4">
                            <img class="card-img-top" src="{% static "img/hh_logo.png" %}" alt="hh">
                        </div>
                        <div class="card-body">
                            <form action="" method="POST" class="d-flex justify-content-center">
                                <div class="form">
                                    {% csrf_token %}
                                    {% bootstrap_form form %}
                                    {% bootstrap_button button_type="submit" content="Log in" button_class="btn-primary btn-block" %}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="d-flex justify-content-center">
                <div class="col-lg-4 col-md-8 col-sm-11">
                    <div class="card">
                        <div class="card-body d-flex justify-content-center">
                            Don't have an account? <a href="{% url "register" %}"><b class="ps-1">Sing Up</b></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/register.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Register </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="row mt-5">
        <div class="d-flex justify-content-center">
            <div class="col-lg-4 col-md-8 col-sm-11">
                <div class="card">
                    <div class="container hh-logo col-5 mt-4">
                        <img class="card-img-top" src="{% static "img/hh_logo.png" %}" alt="hh">
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data">
                            <div class="form">
                                {% csrf_token %}
                                {% bootstrap_field form.username placeholder="" %}
                                <div class="mb-3">
                                    <div class="form-check">
                                        <label class="form-check-label" for="id_is_corporate">Employer account?</label>
                                        <input type="checkbox" name="is_corporate" class="form-check-input"
                                               id="id_is_corporate">
                                    </div>
                                </div>
                                <div class="mb-3" id="first_name_field">
                                    <label class="form-label" for="first_name_input" id="first_name_label">First
                                        name</label>
                                    <label class="form-label" for="first_name_input"
                                           id="company_name_label" style="display: none;">Company Name</label>
                                    <input type="text" name="first_name" maxlength="150" class="form-control"
                                           id="first_name_input">
                                </div>
                                <div class="mb-3" id="second_name_field" style="display: block">
                                    <label class="form-label" for="last_name_input">Last name</label>
                                    <input type="text" name="last_name" maxlength="150" class="form-control"
                                           id="last_name_input">
                                </div>

                                {% bootstrap_field form.email placeholder="" %}
                                {% bootstrap_field form.avatar placeholder="" %}
                                {% bootstrap_field form.phone_number placeholder="" %}
                                {% bootstrap_field form.password1 placeholder="" %}
                                {% bootstrap_field form.password2 placeholder="" %}
                                {% bootstrap_button button_type='submit' content='Register' button_class='btn-primary' %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2 mb-5">
        <div class="d-flex justify-content-center">
            <div class="col-lg-4 col-md-8 col-sm-11">
                <div class="card">
                    <div class="card-body d-flex justify-content-center">
                        Have an account? <a href="{% url "login" %}"><b class="ps-1">Log in</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static "js/is_corporate.js" %}"></script>
</body>
</html>

accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    hh profile
{% endblock %}

{% block modal_window %}
    <div class="modal fade show" id="id-modalUserChange" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container" id="general_profile_info">
       {% include "partial/partial_general_profile_info.html" %}
    </div>

    <div class="container" id="type_related_profile_info">
        {% if user_obj.is_corporate %}
            {% include "partial/corporate_detail.html" %}
        {% else %}
            {% include "partial/employee_detail.html" %}
        {% endif %}
    </div>

{% endblock %}